# Generated by Django 4.1 on 2023-09-18 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_product_sold'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='productImage',
        ),
    ]
