# Generated by Django 4.2.5 on 2023-09-25 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_product_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='User',
            new_name='user',
        ),
    ]
